// export { ReactComponent as PartnersIcon } from "./svg/partners.svg"
export { default as loginBackdrop } from "./img/login-bg.jpg"
export { default as circlesBackdrop } from "./svg/circles.svg"
// export { ReactComponent as Logo } from "./svg/logo.svg"

export { default as PartnersIcon } from "./icons/partners.icon"
export { default as TeamIcon } from "./icons/team.icon"
export { default as VoidIcon } from "./icons/void.icon"
export { default as ServerErrorIcon } from "./icons/server-error.icon"
export { default as AccessIcon } from "./icons/access.icon"
export { default as LogoIcon } from "./icons/logo.icon"
