import { flow } from 'fp-ts/lib/function';
import { prop } from 'ramda';
import { formatDateString } from '../../utils/date';

export const INCIDENT_DATA = [
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
  {
    ref: 'INC0091712',
    service_ref: 'S1234567',
    status: 'new',
    raised_at: new Date(),
    updated_at: new Date(),
    raised_by: 'isabelle.mccabe@cityfibre.com',
  },
];

export const INCIDENT_COLUMNS = [
  {
    Header: 'Incident Reference',
    accessor: 'ref',
    disableFilters: true,
    disableSortBy: true,
  },
  {
    Header: 'Service Reference',
    accessor: 'service_ref',
    disableFilters: true,
    disableSortBy: true,
  },
  {
    Header: 'Status',
    accessor: 'status',
    disableFilters: true,
    disableSortBy: true,
  },
  {
    Header: 'Date Raised',
    accessor: 'raised_at',
    Cell: flow(prop<'value', string>('value'), formatDateString('dd/MM/yyyy')),
    disableFilters: true,
    disableSortBy: true,
  },
  {
    Header: 'Last Updated',
    accessor: 'updated_at',
    Cell: flow(prop<'value', string>('value'), formatDateString('dd/MM/yyyy')),
    disableFilters: true,
    disableSortBy: true,
  },
  {
    Header: 'Raised By',
    accessor: 'raised_by',
    disableFilters: true,
    disableSortBy: true,
  },
] as const;
