export const USER_ROLES = [
  "1st Support Agent",
  "2nd Support Agent",
  "Administrators",
  "Billing Team",
  "Default User",
  "Finance",
  "First Line Ops",
  "First Line Support",
  "First Line Triage",
  "Incident Management",
  "Giganet Roles",
  "Operations Manager",
  "Order Management",
  "Provisioning",
  "Service Desk",
  "Service Executive",
  "Service Management",
  "VOIP Custom Access",
]

export const USER_STATUSES = ["Awaiting Activation", "Active"]

export const USER_DATA = [
  {
    id: 1,
    first_name: "Ernst",
    last_name: "Paxton",
    email: "epaxton0@pcworld.com",
    avatar: "https://robohash.org/providentetaut.png?size=50x50&set=set1",
  },
  {
    id: 2,
    first_name: "Alvan",
    last_name: "Sheddan",
    email: "asheddan1@narod.ru",
    avatar:
      "https://robohash.org/illumreiciendistemporibus.png?size=50x50&set=set1",
  },
  {
    id: 3,
    first_name: "Pen",
    last_name: "Cammish",
    email: "pcammish2@tripadvisor.com",
    avatar:
      "https://robohash.org/voluptatesteneturmolestias.png?size=50x50&set=set1",
  },
  {
    id: 4,
    first_name: "Lynn",
    last_name: "Felten",
    email: "lfelten3@lulu.com",
    avatar: "https://robohash.org/dolorinventoreid.png?size=50x50&set=set1",
  },
  {
    id: 5,
    first_name: "Glynnis",
    last_name: "Miners",
    email: "gminers4@php.net",
    avatar: "https://robohash.org/quisetdolorem.png?size=50x50&set=set1",
  },
  {
    id: 6,
    first_name: "Kiah",
    last_name: "Brok",
    email: "kbrok5@sciencedaily.com",
    avatar:
      "https://robohash.org/utaperiamperspiciatis.png?size=50x50&set=set1",
  },
  {
    id: 7,
    first_name: "Ardisj",
    last_name: "Unger",
    email: "aunger6@noaa.gov",
    avatar: "https://robohash.org/ipsamagnamquos.png?size=50x50&set=set1",
  },
  {
    id: 8,
    first_name: "Rudolph",
    last_name: "Durram",
    email: "rdurram7@printfriendly.com",
    avatar: "https://robohash.org/voluptasinut.png?size=50x50&set=set1",
  },
  {
    id: 9,
    first_name: "Licha",
    last_name: "Heppner",
    email: "lheppner8@ibm.com",
    avatar: "https://robohash.org/etettenetur.png?size=50x50&set=set1",
  },
  {
    id: 10,
    first_name: "Prentice",
    last_name: "Soppeth",
    email: "psoppeth9@goo.gl",
    avatar: "https://robohash.org/magnamquivoluptas.png?size=50x50&set=set1",
  },
  {
    id: 11,
    first_name: "Jaclyn",
    last_name: "Laidlaw",
    email: "jlaidlawa@zdnet.com",
    avatar:
      "https://robohash.org/perspiciatisaperiamillum.png?size=50x50&set=set1",
  },
  {
    id: 12,
    first_name: "Nicolle",
    last_name: "Peachment",
    email: "npeachmentb@unblog.fr",
    avatar: "https://robohash.org/suntsedrerum.png?size=50x50&set=set1",
  },
  {
    id: 13,
    first_name: "Kayley",
    last_name: "Byne",
    email: "kbynec@sun.com",
    avatar: "https://robohash.org/autiuredistinctio.png?size=50x50&set=set1",
  },
  {
    id: 14,
    first_name: "Elwood",
    last_name: "Hodcroft",
    email: "ehodcroftd@fda.gov",
    avatar:
      "https://robohash.org/delenitirepellenduserror.png?size=50x50&set=set1",
  },
  {
    id: 15,
    first_name: "Mercedes",
    last_name: "Robbins",
    email: "mrobbinse@uol.com.br",
    avatar:
      "https://robohash.org/aliquamvoluptatesaccusantium.png?size=50x50&set=set1",
  },
  {
    id: 16,
    first_name: "Quincey",
    last_name: "McNelly",
    email: "qmcnellyf@ehow.com",
    avatar:
      "https://robohash.org/suscipitarchitectoreprehenderit.png?size=50x50&set=set1",
  },
  {
    id: 17,
    first_name: "Noam",
    last_name: "Cresser",
    email: "ncresserg@apache.org",
    avatar: "https://robohash.org/corruptieteos.png?size=50x50&set=set1",
  },
  {
    id: 18,
    first_name: "Bryan",
    last_name: "Hattoe",
    email: "bhattoeh@123-reg.co.uk",
    avatar: "https://robohash.org/essemaioreslibero.png?size=50x50&set=set1",
  },
  {
    id: 19,
    first_name: "Kary",
    last_name: "Jellard",
    email: "kjellardi@hc360.com",
    avatar:
      "https://robohash.org/doloresvoluptatibusharum.png?size=50x50&set=set1",
  },
  {
    id: 20,
    first_name: "Ross",
    last_name: "Andersen",
    email: "randersenj@ca.gov",
    avatar: "https://robohash.org/minusquiadolorum.png?size=50x50&set=set1",
  },
  {
    id: 21,
    first_name: "Agnese",
    last_name: "Brolly",
    email: "abrollyk@networkadvertising.org",
    avatar: "https://robohash.org/quiaipsavoluptatibus.png?size=50x50&set=set1",
  },
  {
    id: 22,
    first_name: "Nicholle",
    last_name: "Calvey",
    email: "ncalveyl@archive.org",
    avatar:
      "https://robohash.org/consequaturdoloremcum.png?size=50x50&set=set1",
  },
  {
    id: 23,
    first_name: "Bevan",
    last_name: "Dundredge",
    email: "bdundredgem@loc.gov",
    avatar: "https://robohash.org/nihilquisquamnihil.png?size=50x50&set=set1",
  },
  {
    id: 24,
    first_name: "Tedie",
    last_name: "Godbold",
    email: "tgodboldn@imgur.com",
    avatar:
      "https://robohash.org/laboriosamnesciuntaut.png?size=50x50&set=set1",
  },
  {
    id: 25,
    first_name: "Jordon",
    last_name: "Wendover",
    email: "jwendovero@gnu.org",
    avatar: "https://robohash.org/autemlaboreet.png?size=50x50&set=set1",
  },
  {
    id: 26,
    first_name: "Kelli",
    last_name: "Kingswood",
    email: "kkingswoodp@pinterest.com",
    avatar: "https://robohash.org/idsitvero.png?size=50x50&set=set1",
  },
  {
    id: 27,
    first_name: "Philomena",
    last_name: "Corrington",
    email: "pcorringtonq@i2i.jp",
    avatar: "https://robohash.org/quiacorporislibero.png?size=50x50&set=set1",
  },
  {
    id: 28,
    first_name: "Ode",
    last_name: "Chisolm",
    email: "ochisolmr@icio.us",
    avatar: "https://robohash.org/sintdoloremeligendi.png?size=50x50&set=set1",
  },
  {
    id: 29,
    first_name: "Hester",
    last_name: "Tuke",
    email: "htukes@google.pl",
    avatar: "https://robohash.org/quisquamautet.png?size=50x50&set=set1",
  },
  {
    id: 30,
    first_name: "Jannelle",
    last_name: "Liles",
    email: "jlilest@mtv.com",
    avatar: "https://robohash.org/beataeullamodit.png?size=50x50&set=set1",
  },
  {
    id: 31,
    first_name: "Neville",
    last_name: "Pritchard",
    email: "npritchardu@dagondesign.com",
    avatar:
      "https://robohash.org/dolorumreprehenderitperferendis.png?size=50x50&set=set1",
  },
  {
    id: 32,
    first_name: "Fredrick",
    last_name: "Duddan",
    email: "fduddanv@dagondesign.com",
    avatar: "https://robohash.org/atomnisid.png?size=50x50&set=set1",
  },
  {
    id: 33,
    first_name: "Staffard",
    last_name: "Ledington",
    email: "sledingtonw@arizona.edu",
    avatar: "https://robohash.org/nullaipsamincidunt.png?size=50x50&set=set1",
  },
  {
    id: 34,
    first_name: "Elmore",
    last_name: "Winwood",
    email: "ewinwoodx@timesonline.co.uk",
    avatar:
      "https://robohash.org/voluptatemestnecessitatibus.png?size=50x50&set=set1",
  },
  {
    id: 35,
    first_name: "Tommi",
    last_name: "Van Velde",
    email: "tvanveldey@upenn.edu",
    avatar:
      "https://robohash.org/voluptatibusenimmolestiae.png?size=50x50&set=set1",
  },
  {
    id: 36,
    first_name: "Pernell",
    last_name: "Crummey",
    email: "pcrummeyz@netvibes.com",
    avatar: "https://robohash.org/autsunteligendi.png?size=50x50&set=set1",
  },
  {
    id: 37,
    first_name: "Emmy",
    last_name: "Mattiello",
    email: "emattiello10@sun.com",
    avatar: "https://robohash.org/rerumsaepeet.png?size=50x50&set=set1",
  },
  {
    id: 38,
    first_name: "Willey",
    last_name: "Fibben",
    email: "wfibben11@dell.com",
    avatar:
      "https://robohash.org/quaeratnecessitatibusrepellendus.png?size=50x50&set=set1",
  },
  {
    id: 39,
    first_name: "Gayel",
    last_name: "Comelini",
    email: "gcomelini12@hao123.com",
    avatar: "https://robohash.org/nonquimagnam.png?size=50x50&set=set1",
  },
  {
    id: 40,
    first_name: "Kristofer",
    last_name: "Boichat",
    email: "kboichat13@flickr.com",
    avatar:
      "https://robohash.org/doloremqueexplicaboesse.png?size=50x50&set=set1",
  },
  {
    id: 41,
    first_name: "Gavin",
    last_name: "Ryburn",
    email: "gryburn14@parallels.com",
    avatar: "https://robohash.org/itaquetemporeid.png?size=50x50&set=set1",
  },
  {
    id: 42,
    first_name: "Orson",
    last_name: "Elnor",
    email: "oelnor15@cbc.ca",
    avatar: "https://robohash.org/nostrumetrepellendus.png?size=50x50&set=set1",
  },
  {
    id: 43,
    first_name: "Lazar",
    last_name: "McComas",
    email: "lmccomas16@lycos.com",
    avatar: "https://robohash.org/velautdolorum.png?size=50x50&set=set1",
  },
  {
    id: 44,
    first_name: "Ruddie",
    last_name: "Redrup",
    email: "rredrup17@51.la",
    avatar: "https://robohash.org/laborumnostrumsint.png?size=50x50&set=set1",
  },
  {
    id: 45,
    first_name: "Court",
    last_name: "Veel",
    email: "cveel18@google.de",
    avatar: "https://robohash.org/autremaut.png?size=50x50&set=set1",
  },
  {
    id: 46,
    first_name: "Ronny",
    last_name: "Scullion",
    email: "rscullion19@home.pl",
    avatar: "https://robohash.org/assumendaametenim.png?size=50x50&set=set1",
  },
  {
    id: 47,
    first_name: "Marcellina",
    last_name: "MacCarter",
    email: "mmaccarter1a@bloglines.com",
    avatar: "https://robohash.org/nihilrepudiandaeet.png?size=50x50&set=set1",
  },
  {
    id: 48,
    first_name: "Bartie",
    last_name: "Barrim",
    email: "bbarrim1b@netscape.com",
    avatar: "https://robohash.org/esterrorquod.png?size=50x50&set=set1",
  },
  {
    id: 49,
    first_name: "Sonny",
    last_name: "Gilley",
    email: "sgilley1c@state.gov",
    avatar: "https://robohash.org/aliquiddictaquia.png?size=50x50&set=set1",
  },
  {
    id: 50,
    first_name: "Lee",
    last_name: "Reith",
    email: "lreith1d@nbcnews.com",
    avatar: "https://robohash.org/quiainventoreet.png?size=50x50&set=set1",
  },
  {
    id: 51,
    first_name: "Stanly",
    last_name: "Bowgen",
    email: "sbowgen1e@cloudflare.com",
    avatar:
      "https://robohash.org/architectorepellatiure.png?size=50x50&set=set1",
  },
  {
    id: 52,
    first_name: "Dynah",
    last_name: "Mogra",
    email: "dmogra1f@dmoz.org",
    avatar: "https://robohash.org/easitpraesentium.png?size=50x50&set=set1",
  },
  {
    id: 53,
    first_name: "Eadmund",
    last_name: "Larchier",
    email: "elarchier1g@networksolutions.com",
    avatar: "https://robohash.org/rerummagnirepellat.png?size=50x50&set=set1",
  },
  {
    id: 54,
    first_name: "Gladys",
    last_name: "Tante",
    email: "gtante1h@github.com",
    avatar: "https://robohash.org/officiaipsamquo.png?size=50x50&set=set1",
  },
  {
    id: 55,
    first_name: "Pearline",
    last_name: "Crielly",
    email: "pcrielly1i@cbsnews.com",
    avatar:
      "https://robohash.org/eaqueblanditiislibero.png?size=50x50&set=set1",
  },
  {
    id: 56,
    first_name: "Goldia",
    last_name: "Meineken",
    email: "gmeineken1j@squarespace.com",
    avatar: "https://robohash.org/doloridut.png?size=50x50&set=set1",
  },
  {
    id: 57,
    first_name: "Clemmie",
    last_name: "Heenan",
    email: "cheenan1k@google.com.hk",
    avatar: "https://robohash.org/eiusipsamolestiae.png?size=50x50&set=set1",
  },
  {
    id: 58,
    first_name: "Antons",
    last_name: "Rauprich",
    email: "arauprich1l@vinaora.com",
    avatar: "https://robohash.org/illocommodienim.png?size=50x50&set=set1",
  },
  {
    id: 59,
    first_name: "Caroljean",
    last_name: "Casino",
    email: "ccasino1m@nationalgeographic.com",
    avatar:
      "https://robohash.org/doloribusquibusdamest.png?size=50x50&set=set1",
  },
  {
    id: 60,
    first_name: "Dara",
    last_name: "Chrippes",
    email: "dchrippes1n@geocities.com",
    avatar: "https://robohash.org/seddoloremvelit.png?size=50x50&set=set1",
  },
  {
    id: 61,
    first_name: "Radcliffe",
    last_name: "Yancey",
    email: "ryancey1o@accuweather.com",
    avatar: "https://robohash.org/quidemmaioresquam.png?size=50x50&set=set1",
  },
  {
    id: 62,
    first_name: "Nero",
    last_name: "Newvell",
    email: "nnewvell1p@sitemeter.com",
    avatar: "https://robohash.org/officiaautemimpedit.png?size=50x50&set=set1",
  },
  {
    id: 63,
    first_name: "Joellen",
    last_name: "Spatari",
    email: "jspatari1q@zimbio.com",
    avatar: "https://robohash.org/etquiaut.png?size=50x50&set=set1",
  },
  {
    id: 64,
    first_name: "Reiko",
    last_name: "Sankey",
    email: "rsankey1r@guardian.co.uk",
    avatar: "https://robohash.org/eosporroquas.png?size=50x50&set=set1",
  },
  {
    id: 65,
    first_name: "Nettie",
    last_name: "Danskine",
    email: "ndanskine1s@shinystat.com",
    avatar:
      "https://robohash.org/minusadipiscivoluptatem.png?size=50x50&set=set1",
  },
  {
    id: 66,
    first_name: "Fredrick",
    last_name: "Lamb-shine",
    email: "flambshine1t@kickstarter.com",
    avatar: "https://robohash.org/corruptinamlaborum.png?size=50x50&set=set1",
  },
  {
    id: 67,
    first_name: "Emanuele",
    last_name: "Eakly",
    email: "eeakly1u@trellian.com",
    avatar: "https://robohash.org/etadalias.png?size=50x50&set=set1",
  },
  {
    id: 68,
    first_name: "Eward",
    last_name: "Parminter",
    email: "eparminter1v@japanpost.jp",
    avatar: "https://robohash.org/harumetsunt.png?size=50x50&set=set1",
  },
  {
    id: 69,
    first_name: "Klement",
    last_name: "Norsworthy",
    email: "knorsworthy1w@infoseek.co.jp",
    avatar:
      "https://robohash.org/magnamnumquamcupiditate.png?size=50x50&set=set1",
  },
  {
    id: 70,
    first_name: "Daniela",
    last_name: "Coppo",
    email: "dcoppo1x@scribd.com",
    avatar:
      "https://robohash.org/reprehenderitmolestiaset.png?size=50x50&set=set1",
  },
  {
    id: 71,
    first_name: "Danita",
    last_name: "Toulmin",
    email: "dtoulmin1y@issuu.com",
    avatar: "https://robohash.org/estrerumvoluptatem.png?size=50x50&set=set1",
  },
  {
    id: 72,
    first_name: "Margalit",
    last_name: "Lissimore",
    email: "mlissimore1z@home.pl",
    avatar:
      "https://robohash.org/consequaturullamdolores.png?size=50x50&set=set1",
  },
  {
    id: 73,
    first_name: "Cristobal",
    last_name: "Norman",
    email: "cnorman20@github.com",
    avatar: "https://robohash.org/earumdoloresaut.png?size=50x50&set=set1",
  },
  {
    id: 74,
    first_name: "Teodora",
    last_name: "Oxton",
    email: "toxton21@digg.com",
    avatar: "https://robohash.org/quislaboriosameum.png?size=50x50&set=set1",
  },
  {
    id: 75,
    first_name: "Egan",
    last_name: "Killiner",
    email: "ekilliner22@admin.ch",
    avatar:
      "https://robohash.org/minimaaccusantiumaspernatur.png?size=50x50&set=set1",
  },
  {
    id: 76,
    first_name: "Nealon",
    last_name: "Tomczykowski",
    email: "ntomczykowski23@engadget.com",
    avatar: "https://robohash.org/aliasvelitvoluptatem.png?size=50x50&set=set1",
  },
  {
    id: 77,
    first_name: "Jeane",
    last_name: "Marshalleck",
    email: "jmarshalleck24@phpbb.com",
    avatar:
      "https://robohash.org/dolorumteneturtempore.png?size=50x50&set=set1",
  },
  {
    id: 78,
    first_name: "Si",
    last_name: "Rapson",
    email: "srapson25@unesco.org",
    avatar:
      "https://robohash.org/fugitlaudantiumfacilis.png?size=50x50&set=set1",
  },
  {
    id: 79,
    first_name: "Jeffrey",
    last_name: "O'Currane",
    email: "jocurrane26@pinterest.com",
    avatar: "https://robohash.org/etculparecusandae.png?size=50x50&set=set1",
  },
  {
    id: 80,
    first_name: "Malvin",
    last_name: "Knowller",
    email: "mknowller27@washington.edu",
    avatar: "https://robohash.org/animiconsequunturaut.png?size=50x50&set=set1",
  },
  {
    id: 81,
    first_name: "Rochella",
    last_name: "Goundrill",
    email: "rgoundrill28@cargocollective.com",
    avatar: "https://robohash.org/estenimqui.png?size=50x50&set=set1",
  },
  {
    id: 82,
    first_name: "Caroline",
    last_name: "Thieme",
    email: "cthieme29@ezinearticles.com",
    avatar: "https://robohash.org/eligendisitsed.png?size=50x50&set=set1",
  },
  {
    id: 83,
    first_name: "Odetta",
    last_name: "Oylett",
    email: "ooylett2a@furl.net",
    avatar: "https://robohash.org/fugitinsed.png?size=50x50&set=set1",
  },
  {
    id: 84,
    first_name: "Afton",
    last_name: "Kaubisch",
    email: "akaubisch2b@alexa.com",
    avatar: "https://robohash.org/estdistinctioin.png?size=50x50&set=set1",
  },
  {
    id: 85,
    first_name: "Kimbell",
    last_name: "Cassie",
    email: "kcassie2c@mapquest.com",
    avatar: "https://robohash.org/abprovidentofficiis.png?size=50x50&set=set1",
  },
  {
    id: 86,
    first_name: "Ilka",
    last_name: "Mulqueeny",
    email: "imulqueeny2d@addtoany.com",
    avatar: "https://robohash.org/sequiinaccusamus.png?size=50x50&set=set1",
  },
  {
    id: 87,
    first_name: "Pauly",
    last_name: "Alenichicov",
    email: "palenichicov2e@pagesperso-orange.fr",
    avatar: "https://robohash.org/sitsitaut.png?size=50x50&set=set1",
  },
  {
    id: 88,
    first_name: "Daune",
    last_name: "Soldner",
    email: "dsoldner2f@addtoany.com",
    avatar: "https://robohash.org/quiaquiplaceat.png?size=50x50&set=set1",
  },
  {
    id: 89,
    first_name: "Mauricio",
    last_name: "Spread",
    email: "mspread2g@kickstarter.com",
    avatar: "https://robohash.org/sedestmaxime.png?size=50x50&set=set1",
  },
  {
    id: 90,
    first_name: "Kissee",
    last_name: "Kramer",
    email: "kkramer2h@gnu.org",
    avatar:
      "https://robohash.org/perferendisconsecteturnesciunt.png?size=50x50&set=set1",
  },
  {
    id: 91,
    first_name: "Yurik",
    last_name: "Rosenfrucht",
    email: "yrosenfrucht2i@mit.edu",
    avatar:
      "https://robohash.org/optioadipiscivoluptates.png?size=50x50&set=set1",
  },
  {
    id: 92,
    first_name: "Arnaldo",
    last_name: "Salerg",
    email: "asalerg2j@skyrock.com",
    avatar: "https://robohash.org/eaaccusantiumin.png?size=50x50&set=set1",
  },
  {
    id: 93,
    first_name: "Horatio",
    last_name: "Braycotton",
    email: "hbraycotton2k@disqus.com",
    avatar: "https://robohash.org/autquosconsequatur.png?size=50x50&set=set1",
  },
  {
    id: 94,
    first_name: "Adelbert",
    last_name: "Ianniello",
    email: "aianniello2l@jiathis.com",
    avatar: "https://robohash.org/cupiditatenatusid.png?size=50x50&set=set1",
  },
  {
    id: 95,
    first_name: "Deanna",
    last_name: "Gouda",
    email: "dgouda2m@surveymonkey.com",
    avatar: "https://robohash.org/quaeratconsequaturex.png?size=50x50&set=set1",
  },
  {
    id: 96,
    first_name: "Filippa",
    last_name: "Ayerst",
    email: "fayerst2n@reverbnation.com",
    avatar: "https://robohash.org/esteosquia.png?size=50x50&set=set1",
  },
  {
    id: 97,
    first_name: "Kassey",
    last_name: "Kemmer",
    email: "kkemmer2o@mediafire.com",
    avatar: "https://robohash.org/etasperioresnon.png?size=50x50&set=set1",
  },
  {
    id: 98,
    first_name: "Hetty",
    last_name: "Osburn",
    email: "hosburn2p@jigsy.com",
    avatar: "https://robohash.org/quoeavelit.png?size=50x50&set=set1",
  },
  {
    id: 99,
    first_name: "Loria",
    last_name: "Braam",
    email: "lbraam2q@simplemachines.org",
    avatar: "https://robohash.org/quamametnemo.png?size=50x50&set=set1",
  },
  {
    id: 100,
    first_name: "Sid",
    last_name: "McNerlin",
    email: "smcnerlin2r@booking.com",
    avatar:
      "https://robohash.org/voluptatemlaborumquia.png?size=50x50&set=set1",
  },
]
