import { FormItem } from "@ui"
import { SimpleGrid, VStack, Input, Textarea, Select } from "@chakra-ui/react"
import { z } from "zod"

const cities = [
  "Aberdare",
  "Aberdeen",
  "Aberdovey",
  "Abergavenny",
  "Abergele",
  "Abertillery",
  "Aberystwyth",
  "Abingdon",
  "Accrington",
  "Airdrie",
  "Alcester",
  "Aldeburgh",
  "Alderley Edge",
  "Aldershot",
  "Alfreton",
  "Alness",
  "Alnwick",
  "Alresford",
  "Alston",
  "Alton",
  "Altrincham",
  "Ambleside",
  "Amersham",
  "Amesbury",
  "Ammanford",
  "Andover",
  "Anstruther",
  "Antrim",
  "Appleby-in-Westmorland",
  "Arbroath",
  "Ardrossan",
  "Armagh",
  "Arthog",
  "Arundel",
  "Ascot",
  "Ashbourne",
  "Ashburton",
  "Ashford",
  "Ashington",
  "Ashtead",
  "Ashton-under-Lyne",
  "Attleborough",
  "Aviemore",
  "Axminster",
  "Aylesbury",
  "Ayr",
  "Bala",
  "Baldock",
  "Ballachulish",
  "Ballycastle",
  "Ballyclare",
  "Ballymena",
  "Ballymoney",
  "Bamburgh",
  "Bamstaple",
  "Banbridge",
  "Banbury",
  "Banchory",
  "Banff",
  "Bangor",
  "Banstead",
  "Barking",
  "Barmouth",
  "Barnard Castle",
  "Barnet",
  "Barnsley",
  "Barnstaple",
  "Barry",
  "Barrow-in Furness",
  "Barton-upon-Humber",
  "Basildon",
  "Basingstoke",
  "Bath",
  "Bathgate",
  "Battle",
  "Beaumaris",
  "Beccles",
  "Beckenham",
  "Bedale",
  "Bedford",
  "Belfast",
  "Belvedere",
  "Benneet",
  "Berkhamsted",
  "Berwick-on-Tweed",
  "Betws-y-Coed",
  "Beverley",
  "Bewdley",
  "Bexhill-on-Sea",
  "Bicester",
  "Bideford",
  "Biggar",
  "Biggleswade",
  "Billericay",
  "Billingshurst",
  "Bingley",
  "Birkenhead",
  "Birmingham",
  "Bishop Auckland",
  "Bishops Castle",
  "Bishop's Stortford",
  "Bishops Waltham",
  "Blackburn",
  "Blackpool",
  "Blaenau Ffestiniog",
  "Blairgowrie",
  "Blandford Forum",
  "Blaydon-on-Tyne",
  "Bodmin",
  "Bognor Regis",
  "Boldon Colliery",
  "Bolton",
  "Bonnyrigg",
  "Bootle",
  "Bordon",
  "Borehamwood",
  "Boston",
  "Botness",
  "Bourne",
  "Bournemouth",
  "Brackley",
  "Bracknell",
  "Bradford",
  "Braintree",
  "Brampton",
  "Braunton",
  "Brecon",
  "Brentford",
  "Brentwood",
  "Bridgend",
  "Bridgnorth",
  "Bridgwater",
  "Bridlington",
  "Bridport",
  "Brigg",
  "Brighouse",
  "Brighton",
  "Bristol",
  "Brixham",
  "Broadford",
  "Broadstairs",
  "Broadway",
  "Brockenhurst",
  "Brodick",
  "Bromley",
  "Bromsgrove",
  "Brooke",
  "Broxburn",
  "Buckfastleigh",
  "Buckhurst Hill",
  "Buckie",
  "Buckingham",
  "Bude",
  "Budleigh Salterton",
  "Builth Wells",
  "Bunessan",
  "Bungay",
  "Burgess Hill",
  "Burnham-on-Sea",
  "Burnley",
  "Burton-on-Trent",
  "Bury",
  "Bury St Edmunds",
  "Bushmills",
  "Buxton",
  "Caernarvon",
  "Caerphilly",
  "Calne",
  "Camberley",
  "Cambridge",
  "Camelford",
  "Campbeltown",
  "Cannock",
  "Canterbury",
  "Cardiff",
  "Cardigan",
  "Carlisle",
  "Carloway",
  "Carluke",
  "Carmarthen",
  "Carnforth",
  "Carrickfergus",
  "Carshalton",
  "Castle Douglas",
  "Castlederg",
  "Castletown",
  "Castlewellan",
  "Caterham",
  "Cemmaes Bay",
  "Cemmaes Road",
  "Cerne Abbas",
  "Chard",
  "Chatham",
  "Chatteris",
  "Cheadle",
  "Cheam",
  "Cheddar",
  "Chelmsford",
  "Cheltenham",
  "Chepstow",
  "Chertsey",
  "Chesham",
  "Chester",
  "Chester-le-Street",
  "Chesterfield",
  "Chichester",
  "Chippenham",
  "Chipping Norton",
  "Chipping Sodbury",
  "Chorley",
  "Christchurch",
  "Church Stretton",
  "Cinderford",
  "Cirencester",
  "Clacton-on-Sea",
  "Cleethorpes",
  "Clevedon",
  "Clitheroe",
  "Clogher",
  "Clopton",
  "Coalville",
  "Coatbridge",
  "Cobham",
  "Cockermouth",
  "Colchester",
  "Coleshill",
  "Coleraine",
  "Colwyn Bay",
  "Congleton",
  "Coniston",
  "Consett",
  "Conwy",
  "Cookstown",
  "Coppull",
  "Corbridge",
  "Corby",
  "Corwen",
  "Coulsdon",
  "Coventry",
  "Craigavon",
  "Cramlington",
  "Cranbrook",
  "Cranleigh",
  "Craven Arms",
  "Crawley",
  "Crediton",
  "Crewe",
  "Crieff",
  "Cromer",
  "Crowborough",
  "Croy",
  "Croydon",
  "Crumlin",
  "Cullompton",
  "Cumnock",
  "Cupar",
  "Cwmbran",
  "Dagenham",
  "Dalbeattie",
  "Dalmally",
  "Dalry",
  "Darlington",
  "Dartford",
  "Darvel",
  "Daventry",
  "Deal",
  "Deeside",
  "Derby",
  "Dereham",
  "Devizes",
  "Dewsbury",
  "Didcot",
  "Dinas Powis",
  "Dingwall",
  "Diss",
  "Dolgellau",
  "Doncaster",
  "Dorchester",
  "Dorking",
  "Dornoch",
  "Douglas",
  "Dover",
  "Downham Market",
  "Downpatrick",
  "Driffield",
  "Droitwich",
  "Dromore",
  "Dudley",
  "Dulverton",
  "Dumbarton",
  "Dumfries",
  "Dunbar",
  "Dunblane",
  "Dundee",
  "Dunfermline",
  "Dungannon",
  "Dunkeld",
  "Dunmow",
  "Dunmurry",
  "Dunoon",
  "Duns",
  "Dunstable",
  "Durham",
  "Dursley",
  "Easingwold",
  "East Grinstead",
  "East Kilbride",
  "East Molesey",
  "Eastbourne",
  "Eastleigh",
  "Ebbsfleet",
  "Ebbw Vale",
  "Edenbridge",
  "Edgware",
  "Edinburgh",
  "Egham",
  "Elgin",
  "Ellesmere Port",
  "Ellon",
  "Ely",
  "Emsworth",
  "Enfeld",
  "Enniskillen",
  "Epping",
  "Epsom",
  "Erith",
  "Esher",
  "Evesham",
  "Exeter",
  "Exmouth",
  "Fakenham",
  "Falkirk",
  "Falmouth",
  "Fareham",
  "Faringdon",
  "Farnborough",
  "Farnham",
  "Felixstowe",
  "Fishguard",
  "Fivemiletown",
  "Fleet",
  "Fleetwood",
  "Flint",
  "Folkestone",
  "Forfar",
  "Fort William",
  "Fortrose",
  "Fowey",
  "Fraserburgh",
  "Freshwater",
  "Frinton-on-Sea",
  "Frome",
  "Gainsborough",
  "Gairloch",
  "Galasheils",
  "Garstang",
  "Gateshead",
  "Gerrards Cross",
  "Gillingham",
  "Girvan",
  "Glamorgan",
  "Glasgow",
  "Glastonbury",
  "Glenrothes",
  "Glossop",
  "Gloucester",
  "Godalming",
  "Godstone",
  "Goole",
  "Gosforth",
  "Gosport",
  "Grange-over-Sands",
  "Grangemouth",
  "Grantham",
  "Gravesend",
  "Grays Thurrock",
  "Great Dunmow",
  "Great Missenden",
  "Great Yarmouth",
  "Greenford",
  "Greenock",
  "Gretna",
  "Grimsby",
  "Guernsey",
  "Guildford",
  "Guisborough",
  "Guiseley",
  "Gullane",
  "Hamilton",
  "Haddington",
  "Hailsham",
  "Halesowen",
  "Halifax",
  "Halstead",
  "Haltwhistle",
  "Hampton",
  "Harlow",
  "Harpenden",
  "Harrogate",
  "Harrow",
  "Hartlepool",
  "Harwich",
  "Haslemere",
  "Hassocks",
  "Hastings",
  "Hatfield",
  "Hathersage",
  "Havant",
  "Haverfordwest",
  "Haverhill",
  "Hawick",
  "Hawkshead",
  "Hay-on-Wye",
  "Hayes",
  "Hayling Island",
  "Haywards Heath",
  "Heanor",
  "Heathfield",
  "Helensburgh",
  "Helmsley",
  "Helston",
  "Hemel Hempstead",
  "Henfield",
  "Henley-on-Thames",
  "Hereford",
  "Herne Bay",
  "Hertford",
  "Hessle",
  "Hexham",
  "Heywood",
  "High Wycombe",
  "Highbridge",
  "Hillsborough",
  "Hinckley",
  "Hindhead",
  "Hitchin",
  "Hockley",
  "Hoddesdon",
  "Holbeach",
  "Holmes Chapel",
  "Holsworthy",
  "Holt",
  "Holyhead",
  "Holywood",
  "Honington",
  "Honiton",
  "Hook",
  "Horley",
  "Hornby",
  "Hornchurch",
  "Hornsea",
  "Horsham",
  "Houghton le Spring",
  "Hounslow",
  "Hove",
  "Huddersfield",
  "Hull",
  "Hungerford",
  "Hunstanton",
  "Huntingdon",
  "Huntly",
  "Hyde",
  "Hythe",
  "Ilford",
  "Ilfracombe",
  "Ilkeston",
  "Ilkley",
  "Immingham",
  "Ingatestone",
  "Insch",
  "Inveraray",
  "Inverness",
  "Inverurie",
  "Iona",
  "Ipstones",
  "Ipswich",
  "Ironbridge",
  "Isle of Wight",
  "Isleworth",
  "Jersey",
  "Johnstone",
  "Keighley",
  "Kelso",
  "Kendal",
  "Kenilworth",
  "Keswick",
  "Kettering",
  "Kidderminster",
  "Kilbirnie",
  "Killin",
  "Killingholme",
  "Kilmacolm",
  "Kilmarnock",
  "King's Lynn",
  "Kings Langley",
  "Kingsbridge",
  "Kingston upon Thames",
  "Kingswinford",
  "Kington",
  "Kingussie",
  "Kirkby Stephen",
  "Kirkcaldy",
  "Kirkwhelpington",
  "Kirriemuir",
  "Knighton",
  "Knutsford",
  "Kyle",
  "Kyleakin",
  "Laindon",
  "Lairg",
  "Lampeter",
  "Lanark",
  "Lancaster",
  "Lancing",
  "Lapworth",
  "Larbert",
  "Latheron",
  "Launceston",
  "Leamington Spa",
  "Leatherhead",
  "Ledbury",
  "Leeds",
  "Leicester",
  "Leigh",
  "Leigh-on-Sea",
  "Leighton Buzzard",
  "Leiston",
  "Leominster",
  "Lerwick",
  "Letchworth",
  "Lewes",
  "Leyburn",
  "Leyland",
  "Lichfield",
  "Lightwater",
  "Limavady",
  "Lincoln",
  "Lingfield",
  "Liphook",
  "Lisburn",
  "Liskeard",
  "Liss",
  "Littleborough",
  "Littlehampton",
  "Liverpool",
  "Livingston",
  "Llanarth",
  "Llanbedr",
  "Llandeilo",
  "Llandovery",
  "Llandrindod Wells",
  "Llandudno",
  "Llandysul",
  "Llanelli",
  "Llangollen",
  "Llanidloes",
  "Llanon",
  "Llanrwst",
  "Llantwit",
  "Llanwrda",
  "Llanwrtyd Wells",
  "Loanhead",
  "Lochboisdale",
  "Lochcarron",
  "Lochgilphead",
  "Lochwinnoch",
  "Lockerbie",
  "London",
  "Londonderry",
  "Loughborough",
  "Loughton",
  "Louth",
  "Lowestoft",
  "Ludlow",
  "Lurgan",
  "Luton",
  "Lutterworth",
  "Lydney",
  "Lymington",
  "Lyndhurst",
  "Lynton",
  "Lytham StAnnes",
  "Macclesfield",
  "Machynlleth",
  "Madingley",
  "Maesteg",
  "Magharafelt",
  "Maidenhead",
  "Maidstone",
  "Maldon",
  "Malmesbury",
  "Malpas",
  "Malton",
  "Malvern",
  "Manchester",
  "Mansfield",
  "March",
  "Margate",
  "Market Drayton",
  "Market Harborough",
  "Market Rasen",
  "Market Weighton",
  "Marlborough",
  "Marlow",
  "Martin",
  "Maryport",
  "Matlock",
  "Maud",
  "Medway",
  "Meifod",
  "Melksham",
  "Melton Mowbray",
  "Mere",
  "Meriden",
  "Merthyr Tydfil",
  "Mexborough",
  "Middlesbrough",
  "Middlewich",
  "Midhurst",
  "Mildenhall",
  "Milford Haven",
  "Milton Keynes",
  "Minehead",
  "Mirfield",
  "Mitcham",
  "Mitcheldean",
  "Mold",
  "Monmouth",
  "Montgomery",
  "Montrose",
  "Morden",
  "Morecambe",
  "Moretonhampstead",
  "Morpeth",
  "Moscow",
  "Motherwell",
  "Musselburgh",
  "Nailsea",
  "Nairn",
  "Nantwich",
  "Narberth",
  "Neath",
  "Nefyn",
  "Nelson",
  "Nethy Bridge",
  "New Malden",
  "New Mills",
  "Newark",
  "Newbury",
  "Newcastle",
  "Newcastle Emlyn",
  "Newcastle upon Tyne",
  "Newcastleton",
  "Newent",
  "Newhaven",
  "Newmarket",
  "Newport",
  "Newport Pagnell",
  "Newquay",
  "Newton Abbot",
  "Newtown",
  "Newtown-le- Willows",
  "Newtownabbey",
  "Newtownards",
  "North Berwick",
  "North Shields",
  "North Walsham",
  "Northallerton",
  "Northampton",
  "Northwich",
  "Northwood",
  "Norwich",
  "Nottingham",
  "Nottinghamshire",
  "Nuneaton",
  "Oakham",
  "Oban",
  "Okehampton",
  "Oldham",
  "Omagh",
  "Ongar",
  "Ormskirk",
  "Orpington",
  "Ossett",
  "Oswestry",
  "Otley",
  "Oxford",
  "Oxted",
  "Paignton",
  "Paisley",
  "Pakenham",
  "Par",
  "Pembroke",
  "Penarth",
  "Pencombe",
  "Penicuik",
  "Penmaenmawr",
  "Penrhyndeudraeth",
  "Penrith",
  "Penryn",
  "Penzance",
  "Pershore",
  "Perth",
  "Peterborough",
  "Peterhead",
  "Petersfield",
  "Petworth",
  "Pevensey",
  "Pewsey",
  "Pickering",
  "Pinner",
  "Pitlochry",
  "Plymouth",
  "Pocklington",
  "Pontefract",
  "Pontyclun",
  "Pontypool",
  "Pontypridd",
  "Poole",
  "Pooley Bridge",
  "Port Isaac",
  "Port Talbot",
  "Porthcawl",
  "Porthmadog",
  "Portree",
  "Portrush",
  "Portsmouth",
  "Potters Bar",
  "Poulton-le-Fylde",
  "Prescot",
  "Prestatyn",
  "Preston",
  "Prestwick",
  "Princes Risborough",
  "Prudhoe",
  "Pulborough",
  "Purley",
  "Pwllheli",
  "No Entries",
  "Radlett",
  "Ramsey",
  "Ramsgate",
  "Raughton Head",
  "Rayleigh",
  "Reading",
  "Redcar",
  "Redditch",
  "Redhill",
  "Redruth",
  "Reigate",
  "Retford",
  "Rhyl",
  "Richmond",
  "Rickmansworth",
  "Riding Mill",
  "Ringwood",
  "Ripley",
  "Ripon",
  "Robertsbridge",
  "Rochdale",
  "Rochester",
  "Rochford",
  "Rockbourne",
  "Romford",
  "Romsey",
  "Ross-on-Wye",
  "Rossendale",
  "Rothbury",
  "Rotherham",
  "Rothesay",
  "Royston",
  "Rugby",
  "Rugeley",
  "Ruislip",
  "Runcorn",
  "Rushden",
  "Ruthin",
  "Rye",
  "Ryton",
  "Saffron Walden",
  "Salford",
  "Salisbury",
  "Saltash",
  "Saltburn-by-the-Sea",
  "Saltcoats",
  "Sandbach",
  "Sandhurst",
  "Sandown",
  "Sandwich",
  "Sandy",
  "Sanquhar",
  "Sawbridgeworth",
  "Saxmundham",
  "Scarborough",
  "Scarinish",
  "Scunthorpe",
  "Seaford",
  "Seaham",
  "Seahouses",
  "Seaton",
  "Sedbergh",
  "Sedgefield",
  "Selby",
  "Selkirk",
  "Settle",
  "Sevenoaks",
  "Shaftesbury",
  "Shap",
  "Shawbost",
  "Sheffield",
  "Shepperton",
  "Shepton Mallet",
  "Sherborne",
  "Sheringham",
  "Shetland",
  "Shifnal",
  "Shipley",
  "Shrewsbury",
  "Sidcup",
  "Sidmouth",
  "Sittingbourne",
  "Skegness",
  "Skelmersdale",
  "Skipton",
  "Sleaford",
  "Slough",
  "Solihull",
  "South Croydon",
  "South Queensferry",
  "South Molton",
  "South Petherton",
  "South Wirral",
  "Southall",
  "Southam",
  "Southampton",
  "Southend-on-Sea",
  "Southminster",
  "Southport",
  "Southsea",
  "Southwell",
  "Sowerby",
  "Spalding",
  "Spilsby",
  "St Albans",
  "St Andrews",
  "St Asaph",
  "St Austell",
  "St Clears",
  "St Helens",
  "St Ives",
  "St Leonards-on-Sea",
  "Stafford",
  "Staines",
  "Stamford",
  "Stanford-le-Hope",
  "Stanmore",
  "Stevenage",
  "Stirling",
  "Stockport",
  "Stocksfield",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Stone",
  "Stonehaven",
  "Stornoway",
  "Stourbridge",
  "Stourport-on-Severn",
  "Stow-on-the-Wold",
  "Stowmarket",
  "Stranraer",
  "Stratford-upon-Avon",
  "Strathcarron",
  "Strathaven",
  "Strathpeffer",
  "Street",
  "Stroud",
  "Sudbury",
  "Sunbury-on-Thames",
  "Sunderland",
  "Surbiton",
  "Sutton",
  "Sutton Coldfield",
  "Sutton-in-Ashfield",
  "Swaffham",
  "Swanage",
  "Swanley",
  "Swansea",
  "Swindon",
  "Tain",
  "Talybont",
  "Tamworth",
  "Tarbert",
  "Tarporley",
  "Taunton",
  "Tavistock",
  "Teddington",
  "Teignmouth",
  "Telford",
  "Temple Cloud",
  "Templecombe",
  "Tenby",
  "Tewkesbury",
  "Thame",
  "Thanet",
  "Thatcham",
  "Thetford",
  "Thirsk",
  "Thornton Heath",
  "Thurso",
  "Tilbury",
  "Tipton",
  "Tiverton",
  "Tonbridge",
  "Torquay",
  "Torrington",
  "Totland Bay",
  "Towcester",
  "Tranent",
  "Tredegar",
  "Tring",
  "Trowbridge",
  "Truro",
  "Tunbridge Wells",
  "Turriff",
  "Twickenham",
  "Tywyn",
  "Uckfield",
  "Ulverston",
  "Umberleigh",
  "Uttoxeter",
  "Uxbridge",
  "Ventnor",
  "Wadebridge",
  "Wakefield",
  "Wallasey",
  "Wallingford",
  "Wallington",
  "Walsall",
  "Walsingham",
  "Waltham Cross",
  "Walton on the Naze",
  "Walton-on-Thames",
  "Wantage",
  "Warboys",
  "Ware",
  "Wareham",
  "Warley",
  "Warminster",
  "Warrington",
  "Warwick",
  "Warwickshire",
  "Washington",
  "Watchet",
  "Watford",
  "Wedmore",
  "Welling",
  "Wellingborough",
  "Wells",
  "Wells-next-the-Sea",
  "Welshpool",
  "Welwyn",
  "Welwyn Garden City",
  "Wem",
  "Wembley",
  "West Bromwich",
  "West Byfleet",
  "West Drayton",
  "West Heslerton",
  "West Kilbride",
  "West Linton",
  "West Malling",
  "West Wickham",
  "Westbury",
  "Westcliff-on-Sea",
  "Westerham",
  "Weston-super-Mare",
  "Wetherby",
  "Weybridge",
  "Weymouth",
  "Whatton",
  "Whitby",
  "Whitchurch",
  "Whitehaven",
  "Whitland",
  "Whitley Bay",
  "Whitstable",
  "Wick",
  "Wickford",
  "Wigan",
  "Wigton",
  "Wilmslow",
  "Wimborne",
  "Wincanton",
  "Winchester",
  "Windermere",
  "Windsor",
  "Winscombe",
  "Wirral",
  "Wisbech",
  "Wishaw",
  "Witham",
  "Witney",
  "Woking",
  "Wokingham",
  "Wolverhampton",
  "Woodford Green",
  "Worcester",
  "Workington",
  "Worksop",
  "Wormbridge",
  "Worthing",
  "Wotton-under-Edge",
  "Wrexham",
  "Wymondham",
  "Yateley",
  "Yelverton",
  "Yeovil",
  "York",
  "Dublin",
  "Cork",
  "Limerick",
  "Galway",
  "Waterford",
  "Drogheda",
  "Kilkenny",
  "Wexford",
  "Sligo",
  "Clonmel",
  "Dundalk",
  "Bray",
  "Navan",
  "Ennis",
  "Tralee",
  "Carlow",
  "Naas",
  "Athlone",
  "Letterkenny",
  "Tullamore",
  "Killarney",
  "Arklow",
  "Cobh",
  "Castlebar",
  "Midleton",
  "Mallow",
  "Ballina",
  "Enniscorthy",
  "Wicklow",
  "Cavan",
  "Athy",
  "Longford",
  "Dungarvan",
  "Nenagh",
  "Trim",
  "New Ross",
  "Thurles",
  "Youghal",
  "Monaghan",
  "Buncrana",
  "Ballinasloe",
  "Fermoy",
  "Westport",
  "Carrick-on-Suir",
  "Kells",
  "Birr",
  "Tipperary",
  "Carrickmacross",
  "Kinsale",
  "Listowel",
  "Clonakilty",
  "Cashel",
  "Macroom",
  "Castleblayney",
  "Kilrush",
  "Skibbereen",
  "Bundoran",
  "Templemore",
  "Clones",
  "Newbridge",
  "Port Laoise",
  "Mullingar",
  "Balbriggan",
  "Greystones",
  "Leixlip",
  "Tramore",
  "Shannon",
  "Gorey",
  "Tuam",
  "Edenderry",
  "Bandon",
  "Passage West",
  "Loughrea",
  "Ardee",
  "Mountmellick",
  "Bantry",
  "Muine Bheag",
  "Boyle",
  "Ballyshannon",
  "Cootehill",
  "Ballybay",
  "Belturbet",
  "Lismore",
  "Kilkee",
  "Granard",
  "Eton",
  "Berwick-upon-Tweed",
]

const defaultValues = {
  location: {
    postcode: "",
    street: "",
    city: "",
  },
  incident: {
    description: "",
    impact: "",
    type: "",
  },
}

const schema = z.object({
  project: z.string().min(1, "This field is required"),
  location: z.object({
    street: z.string().min(1, "This field is required"),
    city: z.string().min(1, "This field is required"),
    postcode: z
      .string()
      .regex(
        /[A-Z]{1,2}[0-9][0-9A-Z]?\s?[0-9][A-Z]{2}/g,
        "Please enter a postal code"
      ),
  }),
  incident: z.object({
    description: z.string().min(1, "This field is required"),
  }),
})

const IncidentDetailsStep = () => (
  <VStack spacing={8} width="100%">
    <SimpleGrid columns={2} spacing={8} w="100%">
      <FormItem
        size="lg"
        isRequired
        name="location.street"
        label="Address / Location"
        render={(props) => <Input {...props} placeholder="Street name" />}
      />
      <FormItem
        size="lg"
        isRequired
        label="City"
        name="location.city"
        render={(props) => (
          <Select {...props} placeholder="Select city">
            {cities.map((city) => (
              <option key={city} value={city}>
                {city}
              </option>
            ))}
          </Select>
        )}
      />
      <FormItem
        size="lg"
        isRequired
        label="Postcode"
        name="location.postcode"
        render={(props) => <Input {...props} placeholder="Postcode" />}
      />
    </SimpleGrid>
    <SimpleGrid columns={2} spacing={8} w="100%">
      <FormItem
        size="lg"
        isRequired
        name="incident.occured_at"
        label="Date/Time of Incident"
        render={(props) => <Input {...props} type="datetime" />}
      />
      <FormItem
        size="lg"
        isRequired
        name="project"
        label="Project"
        render={(props) => (
          <Select {...props}>
            <option value="">None</option>
            <option value="CityFibre">CityFibre</option>
            <option value="BAU">BAU</option>
            <option value="PSN">PSN</option>
            <option value="Ethernet">Entanet</option>
            <option value="FTTH">FTTH</option>
            <option value="MDU">MDU</option>
            <option value="H3G">H3G</option>
            <option value="LDN">LDN</option>
            <option value="Installs">Installs</option>
          </Select>
        )}
      />
      <FormItem
        size="lg"
        name="incident.type"
        label="What type of incident occurred?"
        render={(props) => (
          <Select {...props}>
            <option value="">None</option>
            <option value="Environmental">Environmental Incident</option>
            <option value="Injury">Injury</option>
            <option value="Property Damage">Property Damage</option>
            <option value="Near Miss">Near Miss</option>
            <option value="Strike">Strike</option>
            <option value="COVID-19">COVID-19</option>
            <option value="Other">Other</option>
            <option value="Unsafe Act">UnSafe Act</option>
          </Select>
        )}
      />
      <FormItem
        size="lg"
        name="incident.impact"
        label="What was the impact?"
        render={(props) => (
          <Select {...props}>
            <option value="">None</option>
            <option value="Environmental">Environmental</option>
            <option value="Injury">Injury</option>
            <option value="Equipment">Equipment Damage</option>
            <option value="Strike">Strike</option>
          </Select>
        )}
      />
    </SimpleGrid>
    <FormItem
      size="lg"
      isRequired
      name="incident.description"
      label="Please describe what happened?"
      render={(props) => (
        <Textarea
          {...props}
          placeholder="The who, what, where, when and how..."
        />
      )}
    />
  </VStack>
)

export default {
  label: "Incident Details",
  Step: IncidentDetailsStep,
  isFinalStep: true,
  defaultValues,
  schema,
}
